version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '8080:8080'
    env_file: .env
    depends_on:
      - database

  database:
    image: 'postgres:12.1-alpine'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres: