version: "3" 

services: 
  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    volumes:
      - .:/usr/app/var/lib/postgresql/data
    env_file:
      .env

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    depends_on:
      - postgres
    ports:
      - "8080:8080" 
    volumes:
      - .:/usr/app 
